"""initial migration

Revision ID: ceed0a48fd03
Revises: 
Create Date: 2025-04-22 20:50:48.105576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceed0a48fd03'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historicos')
    op.drop_table('vacinas')
    op.drop_table('diarios')
    op.drop_table('fotos_perfil')
    op.drop_table('saude_pet')
    op.drop_table('usuarios')
    op.drop_table('fotos')
    op.drop_table('pets')
    op.drop_table('medicamentos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicamentos',
    sa.Column('id_med', sa.INTEGER(), nullable=False),
    sa.Column('conteudo', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id_med')
    )
    op.create_table('pets',
    sa.Column('id_pet', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=45), nullable=False),
    sa.Column('data_nascimento', sa.DATE(), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=45), nullable=False),
    sa.Column('cor', sa.VARCHAR(length=45), nullable=True),
    sa.Column('peso', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('raca', sa.VARCHAR(length=45), nullable=True),
    sa.Column('sexo', sa.VARCHAR(length=45), nullable=True),
    sa.Column('id_foto', sa.INTEGER(), nullable=True),
    sa.Column('id_usuario', sa.INTEGER(), nullable=True),
    sa.Column('id_med', sa.INTEGER(), nullable=True),
    sa.Column('id_vac', sa.INTEGER(), nullable=True),
    sa.Column('id_his', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_foto'], ['fotos.id_foto'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_his'], ['historicos.id_his'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_med'], ['medicamentos.id_med'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_vac'], ['vacinas.id_vac'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pet')
    )
    op.create_table('fotos',
    sa.Column('id_foto', sa.INTEGER(), nullable=False),
    sa.Column('foto', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id_foto')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=True),
    sa.Column('senha', sa.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('saude_pet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_pet', sa.INTEGER(), nullable=True),
    sa.Column('vacinas', sa.TEXT(), nullable=True),
    sa.Column('medicamentos', sa.TEXT(), nullable=True),
    sa.Column('doencas', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['id_pet'], ['pets.id_pet'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_pet')
    )
    op.create_table('fotos_perfil',
    sa.Column('id_foto', sa.INTEGER(), nullable=False),
    sa.Column('foto', sa.BLOB(), nullable=False),
    sa.Column('tipo_arquivo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('data_upload', sa.DATE(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id_foto')
    )
    op.create_table('diarios',
    sa.Column('id_diario', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=45), nullable=True),
    sa.Column('conteudo', sa.VARCHAR(length=500), nullable=True),
    sa.Column('id_pet', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_pet'], ['pets.id_pet'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_diario')
    )
    op.create_table('vacinas',
    sa.Column('id_vac', sa.INTEGER(), nullable=False),
    sa.Column('conteudo', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id_vac')
    )
    op.create_table('historicos',
    sa.Column('id_his', sa.INTEGER(), nullable=False),
    sa.Column('conteudo', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id_his')
    )
    # ### end Alembic commands ###
